variables:
  CI: true

trigger:
  paths:
    include:
    - "+gemini3d/*"
    - azure-pipelines.yml

pool:
  vmImage: ubuntu-latest
steps:
  - script: |
      sudo apt update -q
      sudo apt install -yq --no-install-recommends gcc gfortran libhdf5-dev liblapack-dev libmumps-dev libopenmpi-dev openmpi-bin
    displayName: 'Install Linux prereqs'
  - task: InstallMATLAB@0
  - task: RunMATLABCommand@0
    displayName: 'Matlab Version'
    inputs:
      command: disp(version)
  - task: RunMATLABCommand@0
    inputs:
      command: TestGemini
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: test-results/results.xml
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: code-coverage/coverage.xml
