name: matlab

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"
  pull_request:


jobs:
  linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends libhdf5-dev liblapack-dev libmumps-dev libopenmpi-dev openmpi-bin

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install model libraries
      timeout-minutes: 15
      run: |
        cmake -S gemext -B gemext/build -Dfind:BOOL=true -Dmsis2:BOOL=false --install-prefix=${{ runner.temp }}/gemlibs
        cmake --build gemext/build --target ffilesystem glow hwm14 msis
        cmake --install gemext/build

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1

    - name: Install Gemini3D
      timeout-minutes: 15
      uses: matlab-actions/run-command@v1
      with:
        command: setup_gemini3d('${{ runner.temp }}/gemlibs')

    - name: Run Matlab tests
      timeout-minutes: 15
      uses: matlab-actions/run-command@v1
      with:
        command: setup, r = runtests('gemini3d.tests'), assert(~isempty(r)), assertSuccess(r)


# Matlab Windows is in beta, seems a path issue for setup_gemini fails immediately.
  # windows_no_mpi:
  #   # it's tricky to install mpiexec automatically on Windows (see p4est)
  #   # thus it's convenient to use Windows as a no-MPI, no-hwloc test case
  #   timeout-minutes: 20
  #   runs-on: windows-latest

  #   steps:
  #   - uses: msys2/setup-msys2@v2
  #     with:
  #       update: true
  #       install: >-
  #         git
  #         mingw-w64-x86_64-cmake
  #         mingw-w64-x86_64-ninja
  #         mingw-w64-x86_64-gcc-fortran
  #         mingw-w64-x86_64-hdf5
  #         mingw-w64-x86_64-lapack

  #   - name: Put MSYS2_MinGW64 on PATH
  #     # there is not yet an environment variable for this path from msys2/setup-msys2
  #     run: echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

  #   - name: Install MATLAB
  #     uses: matlab-actions/setup-matlab@v1

  #   - name: Run tests and generate artifacts
  #     timeout-minutes: 15
  #     uses: matlab-actions/run-command@v1
  #     with:
  #       command: addpath('${{ env.GITHUB_WORKSPACE }}'), setup_gemini3d, r = runtests('gemini3d.tests'), assert(~isempty(r)), assertSuccess(r)
