name: matlab

env:
  GEMINI_CIROOT: ~/ci
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"

jobs:
  linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: R2022b

    - uses: actions/checkout@v3

    - name: Install Prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends libhdf5-dev liblapack-dev libmumps-dev libopenmpi-dev openmpi-bin

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v3
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install Gemini3D libraries
      timeout-minutes: 15
      run: |
        cmake -S gemext -B gemext/build -Dfind:BOOL=true -Dhwm14:BOOL=false -Dmsis2:BOOL=false -DCMAKE_INSTALL_PREFIX:PATH=${{ runner.temp }}
        cmake --build gemext/build --target ffilesystem iniparser glow hwm14 msis --parallel
        cmake --install gemext/build

    - name: Checkout Gemini3D
      uses: actions/checkout@v3
      with:
        repository: gemini3d/gemini3d
        path: gemini3d

    - name: Install Gemini3D
      timeout-minutes: 15
      run: |
        cmake -S gemini3d -B gemini3d/build -DCMAKE_INSTALL_PREFIX:PATH=${{ runner.temp }}
        cmake --build gemini3d/build --parallel
        cmake --install gemini3d/build

    - name: Run Matlab tests
      timeout-minutes: 15
      uses: matlab-actions/run-command@v1
      with:
        command: buildtool
      env:
        GEMINI_ROOT: ${{ runner.temp }}

# save CI time by not running duplicitive tests
    # - name: CMake config
    #   run: cmake -B build_cmake

    # - name: CMake build
    #   run: cmake --build build_cmake

    # - name: CMake Test
    #   run: ctest --test-dir build_cmake --preset default


# Matlab Windows is in beta, seems a path issue for setup_gemini fails immediately.
  # windows_no_mpi:
  #   # it's tricky to install mpiexec automatically on Windows (see p4est)
  #   # thus it's convenient to use Windows as a no-MPI, no-hwloc test case
  #   timeout-minutes: 20
  #   runs-on: windows-latest

  #   steps:
  #   - uses: msys2/setup-msys2@v2
  #     with:
  #       update: true
  #       install: >-
  #         git
  #         mingw-w64-x86_64-cmake
  #         mingw-w64-x86_64-ninja
  #         mingw-w64-x86_64-gcc-fortran
  #         mingw-w64-x86_64-hdf5
  #         mingw-w64-x86_64-lapack

  #   - name: Put MSYS2_MinGW64 on PATH
  #     # there is not yet an environment variable for this path from msys2/setup-msys2
  #     run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

  #   - name: Install MATLAB
  #     uses: matlab-actions/setup-matlab@v1

  #   - name: Run tests and generate artifacts
  #     timeout-minutes: 15
  #     uses: matlab-actions/run-command@v1
  #     with:
  #       command: addpath('${{ env.GITHUB_WORKSPACE }}'), buildtool
