name: ci

on:
  push:
    paths:
    - "**.m"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        sudo apt -yq update
        sudo apt install -yq --no-install-recommends octave # octave-netcdf

    - run: octave --eval "test_unit"
      working-directory: tests
      env:
        FC: gfortran-9
