name: ci

on:
  push:
    paths:
    - "**/CMakeLists.txt"
    - "**.cmake"
    - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran-9
