name: matlab

env:
  GEMINI_CIROOT: ~/ci
  CMAKE_BUILD_TYPE: Release
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"
    - "!scripts/**"


jobs:

  linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        release: [R2020b, R2021a, R2021b, R2022a, R2022b]
      # R2020a is missing several "mustBe" functions

    steps:

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ matrix.release }}

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v3
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install Prereqs (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo $(cmake -P gemext/scripts/requirements.cmake) libmumps-dev

    - name: Install Prereqs (Macos)
      if: runner.os == 'macOS'
      run: $(cmake -P gemext/scripts/requirements.cmake)

    - name: Install Gemini3D libraries
      timeout-minutes: 15
      run: |
        cmake -B build -Dfind:BOOL=true -DCMAKE_INSTALL_PREFIX:PATH=${{ runner.temp }}
        cmake --build build --parallel
        cmake --install build
      working-directory: gemext

    - name: Checkout Gemini3D
      uses: actions/checkout@v3
      with:
        repository: gemini3d/gemini3d
        path: gemini3d

    - name: Install Gemini3D
      timeout-minutes: 15
      run: |
        cmake -B build -DCMAKE_INSTALL_PREFIX:PATH=${{ runner.temp }} -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }}
        cmake --build build --parallel
        cmake --install build
      working-directory: gemini3d

    - name: Git Checkout ${{ github.action_repository }}
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Run Matlab tests (buildtool)
      if: ${{ matrix.release == 'R2022b' }}
      timeout-minutes: 15
      uses: matlab-actions/run-build@v1
      env:
        GEMINI_ROOT: ${{ runner.temp }}

    - name: Run tests (manual)
      if: ${{ matrix.release != 'R2022b' }}
      timeout-minutes: 15
      uses: matlab-actions/run-command@v1
      with:
        command: |
          r = runtests('gemini3d.test');
          assert(~isempty(r), "No tests were run")
          assertSuccess(r)
      env:
        GEMINI_ROOT: ${{ runner.temp }}

# save CI time by not running duplicitive CMake tests
