name: matlab

env:
  CMAKE_BUILD_TYPE: Release
  CTEST_NO_TESTS_ACTION: error
  CMAKE_GENERATOR: Ninja
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CMAKE_INSTALL_PREFIX: ~/libs
  GEMINI_ROOT: ~/libs

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - "cmake/libraries.json"
    - ".github/workflows/**"
    - "!scripts/**"

# full tests require >= R2023a

# https://www.mathworks.com/support/requirements/supported-compilers-linux.html

# https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/sysreq/files/system-requirements-release-2021b-supported-compilers.pdf
# R2021a, R2021b: GCC-8

# R2022a, R2022b, R2023a, R2023b, R2024a: GCC-10
# https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/sysreq/files/system-requirements-release-2023a-supported-compilers.pdf


jobs:

  linux:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        release: [R2024a, R2023a]
        os: [ubuntu-22.04]

    steps:

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.release }}

    - name: Git Checkout ${{ github.action_repository }}
      uses: actions/checkout@v4
      with:
        submodules: true

    - uses: ./.github/workflows/composite-pkg
      timeout-minutes: 15

    - uses: ./.github/workflows/composite-gemini3d
      timeout-minutes: 15

    - name: Run Matlab tests (buildtool)
      timeout-minutes: 15
      uses: matlab-actions/run-build@v2
      env:
        GEMCI_ROOT: ${{ github.workspace }}/gemci
        GEMINI_CIROOT: ~/ci
