name: matlab

env:
  DEBIAN_FRONTEND: noninteractive
  CTEST_PARALLEL_LEVEL: 2


on:
  push:
    paths:
    - "**.m"
    - ".github/workflows/ci_matlab.yml"


jobs:
  linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Prereqs
        run: |
          sudo apt update -yq
          sudo apt install -yq --no-install-recommends ninja-build gfortran libhdf5-dev liblapack-dev libmumps-dev libopenmpi-dev openmpi-bin

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0

      - name: Config Tests
        run: cmake --preset default

      - name: Run Tests
        run: ctest --preset default
