name: MATLAB on GitHub-Hosted Runner

on:
  push:
    paths:
    - "**.m"
    - ".github/workflows/ci_matlab.yml"


jobs:
  linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Prereqs
        run: |
          sudo apt update -yq
          sudo apt install -yq --no-install-recommends gfortran libhdf5-dev liblapack-dev libmumps-dev libopenmpi-dev openmpi-bin

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0

      - name: Run tests and generate artifacts
        # env:
        #   LD_PRELOAD: /usr/lib/x86_64-linux-gnu/libcurl.so.4
        uses: matlab-actions/run-tests@v0
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
