name: matlab

on:
  push:
    paths:
    - "**.m"
    - ".github/workflows/ci_matlab.yml"


jobs:
  linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Prereqs
        run: |
          sudo apt update -yq
          sudo apt install -yq --no-install-recommends libhdf5-dev liblapack-dev libmumps-dev libopenmpi-dev openmpi-bin

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1

      - run: cmake --preset default
        timeout-minutes: 3

      - run: ctest --preset default
        timeout-minutes: 15
